### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by exekias** [xataio/pgroll#14]
This is the feature set we want as the initial release

## Scope

- Standalone tool that speaks to PostgresSQL to execute migrations (only).
- All supported migrations should be zero-downtime, except for the ones that we are not able to support, or RAW SQL migrations done by the user. By zero-downtime we mean:
    - during the active migration period the old version of the schema keeps working, and work as expected.
    - the new version of the schema will be eventually available during this period, making both of them work at the same time.
- Allow to abort/rollback a migration at any time during the active migration period.
- Define format for migration files (ideally reuse Xata migrations).
- Should be usable both as a CLI and library (for our own purposes).
- Allow to understand existing schemas and run migrations on top.

### Tasks
- [ ] Migrations operations
    -  [x] create table
    -  [x] rename table https://github.com/xataio/pg-roll/pull/23
    -  [x] drop table (https://github.com/xataio/pg-roll/pull/45)
    -  [x] add column
        - [x] delete triggers on rollback
        - [x] backfill existing rows
        - [x] handle adding `NOT NULL` columns without locking.
    -  [x] alter column
        - [x] rename only (https://github.com/xataio/pg-roll/pull/52)
        - [x] change column type (https://github.com/xataio/pg-roll/pull/74)
          - [ ] handle data that can't be converted [[Notion discussion](https://www.notion.so/xata/Research-Zero-downtime-migrations-virtual-schemas-6b12eacd8e4a4a808b1a66c0132fd03b?pvs=4#c640b92e3e384af0abe341960b2b4a1c)]
        - [x] up/down SQL-based migrations
        - [x] constraint changes (different op?)
          - [x] `UNIQUE` constraints: https://github.com/xataio/pg-roll/pull/53 
          - [x] `NOT NULL` constraints: https://github.com/xataio/pg-roll/pull/63
    - [x] drop column (https://github.com/xataio/pg-roll/pull/48)
      - [ ] drop any indexes on the column concurrently? 
    - [x] add index (https://github.com/xataio/pg-roll/pull/49)
      - [ ] Support different index types?
      - [ ] Support partial index?
      - [ ] Support indexes on expressions (like `UPPER(name)`)?
      - [ ] Support more index options, like `NULLS DISTINCT / NULLS FIRST / UNIQUE`?
    - [x] remove index https://github.com/xataio/pg-roll/pull/51
    - [x] add foreign key constraint https://github.com/xataio/pg-roll/pull/82
    - [x] add constraint
    - [x] drop constraint
    - [x] raw SQL https://github.com/xataio/pg-roll/pull/43
- [x] Subcommands:
    - [x] init
    - [x] start
    - [x] complete
    - [x] rollback
    - [x] status https://github.com/xataio/pg-roll/pull/25
- [x] Schema representation & View creation
- [x] Migration files
    - [x] validation https://github.com/xataio/pg-roll/pull/27
- [ ] Documentation
  - [x] https://github.com/xataio/pg-roll/pull/70
- [ ] Makefile for common operations: `test`, `fmt`, `lint`.
- [x] #47
- [ ] Tests
  - [x] matrix for (14+) (https://github.com/xataio/pg-roll/pull/46)
