### ISSUE TITLE
[Launch] Get ready for first launch 

### ISSUE THREAD

**Issue by monicasarbu** [xataio/pgroll#95]
The tasks that need to be done to have pg-roll open source:
Note: For the first version, we decided not have a dedicate website, and treat it as a stand alone OSS project. All the information about installing, using pg-roll would be in Github. 

```[tasklist]
### Tasks
- [x] Finalise the name. For now it's pg-roll, and another alternative is pgroll @monicasarbu
- [x] One liner: Suggestion "Zero-downtime schema migration tool for Postgres"
- [x] Build a logo and banner @miukimiu #136
- [x] Readme file @exekias https://github.com/xataio/pg-roll/pull/115
- [x] Docs @exekias & @andrew-farries
- [x] LICENSE https://github.com/xataio/pg-roll/pull/111
- [x] contributing.md (optional)
- [ ] blog post for the launch @alexfrancoeur
- [x] video with the latest demo @andrew-farries [[Rewatch](https://xata.rewatch.com/video/wa7lcpb0x9p7nje6-pg-roll-demo)]
- [x] folding unique constraint into alter_column @andrew-farries https://github.com/xataio/pg-roll/pull/116
- [x] improve experience with existing dbs @exekias https://github.com/xataio/pg-roll/pull/112
- [ ] eject/uninstall command @exekias
```

**Comment by exekias** [comment]
release ready 🚀
